[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@sp1-contracts/=./lib/sp1-contracts/contracts/src/",
    "@forge-std/=./lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "https://sepolia.dev"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/demo"

# [etherscan]
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
